hope this works...

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -20,16 +20,25 @@ environment:
 
 # do not indent -ps and leave line break the way it is!
 init:
-- ps: >-
+  - ps: |
     $app = Get-WmiObject -Class Win32_Product -Filter "Vendor = 'http://golang.org'"
 
     if ($app) {
       $app.Uninstall()
     }
-- git config --global core.autocrlf input    
+  - git config --global core.autocrlf input
 
 # scripts that run after cloning repository
 install:
+  - dir c:\
+  - ps: |
+      curl -outfile mw64.7z "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z";
+      if((Get-FileHash mw64.7z -Algorithm SHA1).Hash -ne "91A35AE296C1A71802AB0C7228EE57F9AAC5D7C7")
+      {
+          echo "Invalid file hash";
+          exit 1;
+      };
+      7z x -oC:\ mw64.7z | out-null;
   - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
   - appveyor DownloadFile https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi
   - msiexec /i go1.4.2.windows-amd64.msi /q
@@ -39,15 +48,7 @@ install:
   - go get -u golang.org/x/tools/cmd/cover
   - go get -u github.com/tischda/go2xunit
   - go get -u github.com/AllenDang/w32
-  - dir c:\
-  - ps: curl -outfile mw64.7z "http://libgd.blob.core.windows.net/mingw/x86_64-4.9.1-release-posix-seh-rt_v3-rev1.7z";
-  - ps: if((Get-FileHash mw64.7z -Algorithm SHA1).Hash -ne "91A35AE296C1A71802AB0C7228EE57F9AAC5D7C7")
-        {
-          echo "Invalid file hash";
-          exit 1;
-        };
-  - ps: 7z x -oC:\ mw64.7z | out-null;
-  
+
 # to run your custom scripts instead of automatic MSBuild
 build_script:
   - cd %APPVEYOR_BUILD_FOLDER%
